[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_TMDB_API_KEY = "ee0523e68507cbdbecab924bcdae73ec"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"